name: Mannual Integration tests 
on: 
  workflow_dispatch:
    inputs:
      component_repo_owner:
        description: 'Owner Of component repo'     
        required: true
        default: 'wso2'
      component_repo_name:
        description: 'Name Of the component repo'     
        required: false
        default: 'carbon-apimgt' 
      component_branch:
        description: 'Component branch Name'     
        required: true
        default: 'master'
      product_repo_owner:
        description: 'Owner Of product repo'     
        required: true
        default: 'wso2'
      product_repo_name:
        description: 'Name Of product repo'     
        required: false
        default: 'product-apim' 
      product_branch:
        description: 'Product branch Name'     
        required: true
        default: 'master'
jobs:
  build-carbon:
    runs-on: ubuntu-latest
    steps:
      - name: Run hostname
        run: hostname
      - name: Fix host entry
        run: sudo echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts
      - name: Show hosts
        run: cat /etc/hosts
      - name: Checkout module-refactor
        uses: actions/checkout@v2
        with: 
          repository: ${{ github.event.inputs.component_repo_owner }}/${{ github.event.inputs.component_repo_name }}
          ref: refs/heads/${{ github.event.inputs.component_branch }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 8.0.282+8
          distribution: 'adopt'
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2
      - name: Build carbon-apimgt with Tests, skipping AspectJ
        run: mvn clean install --file pom.xml -Dskip.aspectj=true
  run-benchmark-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run hostname
        run: hostname
      - name: Fix host entry
        run: sudo echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts
      - name: Show hosts
        run: cat /etc/hosts
      - name: Checkout carbon apimgt
        uses: actions/checkout@v2
        with: 
          repository: ${{ github.event.inputs.component_repo_owner }}/${{ github.event.inputs.component_repo_name }}
          ref: refs/heads/${{ github.event.inputs.component_branch }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: 8.0.282+8
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2
      - name: Build carbon-apimgt without Test.
        run: mvn clean install -DskipTests --file pom.xml
      - name: Get carbon.apimgt.version
        run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout > ../CARBON_APIMGT_VERSION_FILE
      - name: Print carbon.apimgt.version
        run: |
          echo $(cat ../CARBON_APIMGT_VERSION_FILE)
          echo ${{ github.event.inputs.component_repo_owner }}/${{ github.event.inputs.component_repo_name }}/${{ github.event.inputs.component_branch }}
          echo ${{ github.event.inputs.product_repo_owner }}/${{ github.event.inputs.product_repo_name }}/${{ github.event.inputs.product_branch }}
      - name: Checkout Product-APIM
        uses: actions/checkout@v2
        with: 
          repository: ${{ github.event.inputs.product_repo_owner }}/${{ github.event.inputs.product_repo_name }}
          ref: refs/heads/${{ github.event.inputs.product_branch }}
          path: product-apim
      - name: Build Product-Apim with Maven
        run: mvn clean install -Dcarbon.apimgt.version=$(cat ../CARBON_APIMGT_VERSION_FILE) -fae --file product-apim/pom.xml -DskipIntegrationTests=true
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - id: 1
            segment: apim-integration-tests-api-common,apim-integration-tests-api-change-endpoint,apim-CORS-tests
          - id: 2
            segment: apim-email-secondary-userstore-tests
          - id: 3
            segment: apim-integration-tests-samples,apim-store-tests,apim-integration-tests-graphql,admin-rest-api-tests,rest-api-tests,apim-mediation-tests
          - id: 4
            segment: apim-streaming-api-tests,apim-JWT-integration-tests
          - id: 5
            segment: apim-websocket-tests,apim-integration-tests-application-sharing,apim-integration-tests-api-product
          - id: 6
            segment: apim-integration-tests-api-lifecycle,apim-integration-tests-api-lifecycle-2
          - id: 7
            segment: apim-publisher-tests,apim-solace-broker-tests
          - id: 8
            segment: apim-integration-tests-without-restarts,apim-integration-tests-without-advance-throttling,apim-urlsafe-JWT-integration-tests
          - id: 9
            segment: apim-integration-tests-external-idp,apim-integration-tests-workflow
          - id: 10
            segment: apim-integration-tests-endpoint-security,apim-integration-emailusername-login 
      fail-fast: false
    steps:
    - name: Run hostname
      run: hostname
    - name: Fix host entry
      run: sudo echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts
    - name: Show hosts
      run: cat /etc/hosts
    - name: Checkout module-refactor
      uses: actions/checkout@v2
      with: 
        repository: ${{ github.event.inputs.component_repo_owner }}/${{ github.event.inputs.component_repo_name }}
        ref: refs/heads/${{ github.event.inputs.component_branch }}

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: 8.0.282+8
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
    - name: Build carbon-apimgt without Test.
      run: mvn clean install -DskipTests --file pom.xml
    - name: Get carbon.apimgt.version
      run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout > ../CARBON_APIMGT_VERSION_FILE
    - name: Print carbon.apimgt.version
      run: |
        echo $(cat ../CARBON_APIMGT_VERSION_FILE)
        echo ${{ github.event.inputs.component_repo_owner }}/${{ github.event.inputs.component_repo_name }}/${{ github.event.inputs.component_branch }}
        echo ${{ github.event.inputs.product_repo_owner }}/${{ github.event.inputs.product_repo_name }}/${{ github.event.inputs.product_branch }}
    - name: Checkout Product-APIM
      uses: actions/checkout@v2
      with: 
        repository: ${{ github.event.inputs.product_repo_owner }}/${{ github.event.inputs.product_repo_name }}
        ref: refs/heads/${{ github.event.inputs.product_branch }}
        path: product-apim
    - name: Build Product-Apim with Maven
      run: mvn clean install -Dcarbon.apimgt.version=$(cat ../CARBON_APIMGT_VERSION_FILE) -fae --file product-apim/pom.xml -DskipBenchMarkTest=true
      env:
        PRODUCT_APIM_TESTS: ${{ matrix.segment }}
    - name: Prepare upload testng report
      if: always()
      run: mv product-apim/modules/integration/tests-integration/tests-backend/target/surefire-reports/TEST-TestSuite.xml TEST-TestSuite_${{ matrix.id }}.xml
    - name: Archive testng report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: TEST-TestSuite_${{ matrix.id }}
        path: |
          TEST-TestSuite_${{ matrix.id }}.xml
        if-no-files-found: warn
  show-report:
    if: always()
    needs: build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: reports
      - name: Publish Test Report
        if: always()
        uses: malinthaprasan/action-surefire-report@v1
        with:
          report_paths: 'reports/**/TEST-*.xml'